AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
Metrics/LineLength:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
