#!/usr/bin/env ruby -v

require_relative 's3config.rb'

@s3 = ::Aws::S3::Client.new

bucket = ENV['s3_bucket']

dirname = 'real-data'
unless File.directory?(dirname)
  FileUtils.mkdir_p(dirname)
end
datayamlpath = File.expand_path("#{dirname}/#{bucket}.yaml",  __FILE__)

File.open(datayamlpath, 'w') do |file|
  response = @s3.get_object(bucket: bucket, key: 'data.yaml')
  file << response.body.read
end
